[2024-06-06 13:01:45,591: INFO: main: Welcome to our custom classifier!]
[2024-06-06 13:14:31,423: INFO: main: Welcome to our custom logs!]
[2024-06-06 14:40:24,667: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 14:40:24,667: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 14:40:24,667: INFO: common: created directory at: artifacts]
[2024-06-06 14:40:24,680: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 14:40:24,681: INFO: 1579108944: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 14:41:17,740: INFO: 1579108944: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 14:56:13,020: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 14:56:13,020: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 14:56:13,020: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 14:56:13,020: INFO: common: created directory at: artifacts]
[2024-06-06 14:56:13,020: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 14:56:13,020: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 14:56:59,614: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 14:57:00,218: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 15:17:26,568: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:17:26,573: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:17:26,573: INFO: common: created directory at: artifacts]
[2024-06-06 15:17:26,573: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 15:18:24,230: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 15:26:09,151: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 15:26:09,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:26:09,151: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:26:09,151: INFO: common: created directory at: artifacts]
[2024-06-06 15:26:09,151: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 15:26:09,151: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 15:27:02,809: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 15:27:03,350: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 15:27:03,350: INFO: main: *******************]
[2024-06-06 15:27:03,350: INFO: main: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 15:27:03,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:27:03,366: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:27:03,366: INFO: common: created directory at: artifacts]
[2024-06-06 15:27:03,366: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 15:27:03,728: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 15:27:03,961: INFO: main: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 15:37:45,714: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:37:45,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:37:45,714: INFO: common: created directory at: artifacts]
[2024-06-06 15:37:45,714: INFO: common: created directory at: artifacts\training]
[2024-06-06 15:46:33,908: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 15:46:33,908: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:46:33,908: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:46:33,908: INFO: common: created directory at: artifacts]
[2024-06-06 15:46:33,908: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 15:46:33,908: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 15:47:19,293: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 15:47:20,077: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 15:47:20,077: INFO: main: *******************]
[2024-06-06 15:47:20,077: INFO: main: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 15:47:20,093: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:47:20,093: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:47:20,093: INFO: common: created directory at: artifacts]
[2024-06-06 15:47:20,093: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 15:47:20,457: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 15:47:20,651: INFO: main: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 15:47:20,651: INFO: main: *******************]
[2024-06-06 15:47:20,651: INFO: main: >>>>>> stage Training Model Stage started <<<<<<]
[2024-06-06 15:47:20,653: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 15:47:20,655: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 15:47:20,655: INFO: common: created directory at: artifacts]
[2024-06-06 15:47:20,656: INFO: common: created directory at: artifacts\training]
[2024-06-06 15:47:56,630: INFO: main: >>>>>> stage Training Model Stage completed <<<<<<

x==========x]
[2024-06-06 19:54:21,171: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 19:54:21,178: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 19:54:21,178: INFO: common: created directory at: artifacts]
[2024-06-06 19:54:32,652: INFO: common: json file saved at: scores.json]
[2024-06-06 19:54:35,948: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 19:54:36,524: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmpzztc3d9q\model\data\model\assets]
[2024-06-06 20:07:18,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:07:18,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:07:18,904: INFO: common: created directory at: artifacts]
[2024-06-06 20:07:30,552: INFO: common: json file saved at: scores.json]
[2024-06-06 20:07:33,564: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 20:07:34,119: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmpjxjfa925\model\data\model\assets]
[2024-06-06 20:11:59,695: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:11:59,706: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:11:59,706: INFO: common: created directory at: artifacts]
[2024-06-06 20:12:11,413: INFO: common: json file saved at: scores.json]
[2024-06-06 20:12:14,599: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 20:12:15,212: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmp9kqocn9k\model\data\model\assets]
[2024-06-06 20:25:33,771: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 20:25:33,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:25:33,787: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:25:33,787: INFO: common: created directory at: artifacts]
[2024-06-06 20:25:33,787: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 20:25:33,787: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:26:50,769: ERROR: main: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))]
Traceback (most recent call last):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\ALIENWARE M15\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "C:\Users\ALIENWARE M15\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\ALIENWARE M15\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\ALIENWARE M15\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\ALIENWARE M15\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\urllib3\response.py", line 593, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\ALIENWARE M15\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\urllib3\response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\main.py", line 11, in <module>
    obj.main()
  File "d:\dev\kidney-disease-detection-with-deep-learning\src\kidneyDiseaseClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\dev\kidney-disease-detection-with-deep-learning\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 31, in download_file
    raise e
  File "d:\dev\kidney-disease-detection-with-deep-learning\src\kidneyDiseaseClassifier\components\data_ingestion.py", line 26, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\gdown\download.py", line 368, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[2024-06-06 20:28:28,051: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 20:28:28,051: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:28:28,051: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:28:28,051: INFO: common: created directory at: artifacts]
[2024-06-06 20:28:28,051: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 20:28:28,051: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:31:33,898: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:31:34,480: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 20:31:34,480: INFO: main: *******************]
[2024-06-06 20:31:34,480: INFO: main: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 20:31:34,480: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:31:34,480: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:31:34,480: INFO: common: created directory at: artifacts]
[2024-06-06 20:31:34,480: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 20:31:34,861: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 20:31:35,063: INFO: main: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:31:35,064: INFO: main: *******************]
[2024-06-06 20:31:35,064: INFO: main: >>>>>> stage Training Model Stage started <<<<<<]
[2024-06-06 20:31:35,066: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:31:35,069: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:31:35,069: INFO: common: created directory at: artifacts]
[2024-06-06 20:31:35,070: INFO: common: created directory at: artifacts\training]
[2024-06-06 20:32:10,577: INFO: main: >>>>>> stage Training Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:32:10,577: INFO: main: *******************]
[2024-06-06 20:32:10,577: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-06-06 20:32:10,588: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:32:10,590: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:32:10,591: INFO: common: created directory at: artifacts]
[2024-06-06 20:32:22,154: INFO: common: json file saved at: scores.json]
[2024-06-06 20:32:23,670: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 20:32:24,250: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmpvc3g3xly\model\data\model\assets]
[2024-06-06 20:32:32,448: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x]
[2024-06-06 20:35:57,872: INFO: helpers: Initialized MLflow to track repo "calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning"]
[2024-06-06 20:35:57,872: INFO: helpers: Repository calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning initialized!]
[2024-06-06 20:35:57,872: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 20:35:57,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:35:57,872: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:35:57,872: INFO: common: created directory at: artifacts]
[2024-06-06 20:35:57,872: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 20:35:57,872: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:37:07,418: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:37:08,008: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 20:37:08,008: INFO: main: *******************]
[2024-06-06 20:37:08,008: INFO: main: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 20:37:08,008: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:37:08,008: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:37:08,008: INFO: common: created directory at: artifacts]
[2024-06-06 20:37:08,008: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 20:37:08,366: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 20:37:08,566: INFO: main: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:37:08,567: INFO: main: *******************]
[2024-06-06 20:37:08,567: INFO: main: >>>>>> stage Training Model Stage started <<<<<<]
[2024-06-06 20:37:08,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:37:08,571: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:37:08,571: INFO: common: created directory at: artifacts]
[2024-06-06 20:37:08,572: INFO: common: created directory at: artifacts\training]
[2024-06-06 20:37:44,548: INFO: main: >>>>>> stage Training Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:37:44,549: INFO: main: *******************]
[2024-06-06 20:37:44,549: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-06-06 20:37:44,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:37:44,553: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:37:44,554: INFO: common: created directory at: artifacts]
[2024-06-06 20:37:56,264: INFO: common: json file saved at: scores.json]
[2024-06-06 20:37:59,020: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 20:37:59,551: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmp74erbvb_\model\data\model\assets]
[2024-06-06 20:39:20,899: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x]
[2024-06-06 20:39:58,659: INFO: helpers: Initialized MLflow to track repo "calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning"]
[2024-06-06 20:39:58,659: INFO: helpers: Repository calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning initialized!]
[2024-06-06 20:39:58,659: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 20:39:58,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:39:58,659: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:39:58,659: INFO: common: created directory at: artifacts]
[2024-06-06 20:39:58,659: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 20:39:58,659: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:41:02,754: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:41:03,217: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 20:41:03,217: INFO: main: *******************]
[2024-06-06 20:41:03,217: INFO: main: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 20:41:03,217: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:41:03,217: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:41:03,217: INFO: common: created directory at: artifacts]
[2024-06-06 20:41:03,217: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 20:41:03,591: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 20:41:04,482: INFO: main: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:41:04,482: INFO: main: *******************]
[2024-06-06 20:41:04,482: INFO: main: >>>>>> stage Training Model Stage started <<<<<<]
[2024-06-06 20:41:04,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:41:04,482: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:41:04,482: INFO: common: created directory at: artifacts]
[2024-06-06 20:41:04,482: INFO: common: created directory at: artifacts\training]
[2024-06-06 20:42:16,140: INFO: main: >>>>>> stage Training Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:42:16,140: INFO: main: *******************]
[2024-06-06 20:42:16,140: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-06-06 20:42:16,140: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:42:16,151: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:42:16,153: INFO: common: created directory at: artifacts]
[2024-06-06 20:42:27,992: INFO: common: json file saved at: scores.json]
[2024-06-06 20:42:30,800: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 20:42:31,329: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmpb1ptdckh\model\data\model\assets]
[2024-06-06 20:43:44,482: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x]
[2024-06-06 20:45:37,987: INFO: helpers: Initialized MLflow to track repo "calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning"]
[2024-06-06 20:45:37,987: INFO: helpers: Repository calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning initialized!]
[2024-06-06 20:45:37,987: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 20:45:37,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:45:37,987: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:45:37,987: INFO: common: created directory at: artifacts]
[2024-06-06 20:45:37,987: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 20:45:37,987: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:46:58,974: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 20:46:59,436: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 20:46:59,436: INFO: main: *******************]
[2024-06-06 20:46:59,436: INFO: main: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 20:46:59,436: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:46:59,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:46:59,451: INFO: common: created directory at: artifacts]
[2024-06-06 20:46:59,451: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 20:46:59,809: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 20:47:01,055: INFO: main: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:47:01,055: INFO: main: *******************]
[2024-06-06 20:47:01,055: INFO: main: >>>>>> stage Training Model Stage started <<<<<<]
[2024-06-06 20:47:01,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:47:01,055: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:47:01,055: INFO: common: created directory at: artifacts]
[2024-06-06 20:47:01,055: INFO: common: created directory at: artifacts\training]
[2024-06-06 20:48:52,108: INFO: main: >>>>>> stage Training Model Stage completed <<<<<<

x==========x]
[2024-06-06 20:48:52,108: INFO: main: *******************]
[2024-06-06 20:48:52,108: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-06-06 20:48:52,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 20:48:52,108: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 20:48:52,108: INFO: common: created directory at: artifacts]
[2024-06-06 20:49:04,073: INFO: common: json file saved at: scores.json]
[2024-06-06 20:49:07,052: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-06-06 20:49:07,581: INFO: builder_impl: Assets written to: C:\Users\ALIENW~1\AppData\Local\Temp\tmpulh3uj2z\model\data\model\assets]
[2024-06-06 20:50:46,525: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x]
[2024-06-06 21:11:13,943: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-06-06 21:11:13,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 21:11:13,943: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 21:11:13,943: INFO: common: created directory at: artifacts]
[2024-06-06 21:11:13,943: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-06 21:11:13,943: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 21:13:41,754: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-06 21:13:42,457: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x==========x]
[2024-06-06 21:13:51,159: INFO: stage_02_prepare_base_model: *******************]
[2024-06-06 21:13:51,159: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage started <<<<<<]
[2024-06-06 21:13:51,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 21:13:51,159: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 21:13:51,159: INFO: common: created directory at: artifacts]
[2024-06-06 21:13:51,159: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-06 21:13:51,576: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-06 21:13:51,876: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model Stage completed <<<<<<

x==========x]
[2024-06-06 21:13:57,266: INFO: stage_03_model_training: *******************]
[2024-06-06 21:13:57,266: INFO: stage_03_model_training: >>>>>> stage Training Model Stage started <<<<<<]
[2024-06-06 21:13:57,266: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 21:13:57,266: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 21:13:57,266: INFO: common: created directory at: artifacts]
[2024-06-06 21:13:57,266: INFO: common: created directory at: artifacts\training]
[2024-06-06 21:15:44,213: INFO: stage_03_model_training: >>>>>> stage Training Model Stage completed <<<<<<

x==========x]
[2024-06-06 21:15:51,747: INFO: helpers: Initialized MLflow to track repo "calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning"]
[2024-06-06 21:15:51,747: INFO: helpers: Repository calvinsendawula/Kidney-Disease-Detection-With-Deep-Learning initialized!]
[2024-06-06 21:15:51,747: INFO: stage_04_model_evaluation: *******************]
[2024-06-06 21:15:51,747: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-06-06 21:15:51,747: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-06 21:15:51,758: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-06 21:15:51,759: INFO: common: created directory at: artifacts]
[2024-06-06 21:16:04,122: INFO: common: json file saved at: scores.json]
[2024-06-06 21:16:04,122: INFO: stage_04_model_evaluation: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x]
[2024-06-06 23:26:06,210: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.18.3:8080]
[2024-06-06 23:26:06,210: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-06 23:26:19,004: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:26:19] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:27:02,194: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "d:\dev\kidney-disease-detection-with-deep-learning\src\kidneyDiseaseClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-06-06 23:27:02,211: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:27:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-06 23:28:06,410: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:28:06] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:28:50,998: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.18.3:8080]
[2024-06-06 23:28:50,998: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-06 23:28:57,218: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:28:57] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:29:02,662: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "d:\dev\kidney-disease-detection-with-deep-learning\src\kidneyDiseaseClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-06-06 23:29:02,662: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:29:02] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-06 23:29:10,617: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:29:10] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:33:11,030: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.18.3:8080]
[2024-06-06 23:33:11,030: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-06 23:33:15,095: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:33:15] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:33:22,293: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:33:22] "POST /predict HTTP/1.1" 200 -]
[2024-06-06 23:33:39,806: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:33:39] "POST /predict HTTP/1.1" 200 -]
[2024-06-06 23:35:32,683: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.18.3:8080]
[2024-06-06 23:35:32,683: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-06 23:35:35,121: ERROR: app: Exception on / [GET]]
Traceback (most recent call last):
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\app.py", line 25, in home
    return render_template('index.html')
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\kidney_disease_venv\lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Dev\Kidney-Disease-Detection-With-Deep-Learning\templates\index.html", line 138, in template
    {% comment %} <img class="logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIkAAAAlCAMAAABBJDpuAAAAVFBMVEX/fgD/iQA7NzIyMjMnNYInNYEnNYInNYEzMzInNYQnNYETJzsnNYIwN1wxMjNoTis4O1YrNm0xOF47PE9DP0dEQEVpTVkAJJ4nNYEOLJHJbiAzMzOmmmHRAAAAFnRSTlOh/vu+986oen9fP2UqEzQkFAIDAAEEILVBJQAAA3FJREFUWMPNmO2WoyAMQG0VBARtdVRs3/89NwkgaF1rd2aOm18tIrnkgwSz7n+R7LcV1ELkeS7E7VySRlyfQXJhTiO55c+liP4cEuH1X8E7gaV+S3Jv2zYZ/Vr+/Sdx2vP6doc/fSPcf/GOpLSFVXFUW8t+giRP47TOd60yk1hbxIhSP0ACKPWrvw7YBIT/lcQY84G3Wk17ugWQfg5UsQJpjflKSLQi7xTWyk0SXTJ4VnB5D1yccxmp4Z+mX5KGNS+SPXVNll0ulyxL0wYmloBB6zL/MpCoAgjAJiUM6w0SboMwPUdRogvNKcNM3smFdRvEcJJkKcflQa+X0pNIfBGW0zKqjyQtw4VLKQlI7ZLgdrRNSZDjMQx2GB4pCkxkCrfGWUTJ0Egan6muCHgJCUwtnCk0mrJ9Q8K5LUqtdSfynkAedhynaRqngVDaXLiJEAzkFkM71IuIlWRYtSQpbXSZDvQ7JPCei9brs+oaABkn74LRIkpFaVxGnzjvIxTYREOoEwn5r01JTDRTcO87Eu3zNUeTPKZpjrIRrNIDCjzALbPk7LJMIokOEQu2K7yKQAKvFDF9pVe0R+LGb7h1MMkw2ijjA/1zhSfSphvEAChXJEhAqwYStIJWXnTpvbdH4hTUwSQ2JRmQpILDLYbB7J41SYiLcNozu5Z3JMo7RxBJahI7WSRByCMkqJt9hySESbVJcvmARJGFExJmdBSl2oM2+T4JLWfgaGFptizlPUm1FydHSdyZ7UnS4ySph2kS0kJrkvr5NJg7dnrJnfxgxPozRPGtkyPNOxtaiDvbIAF9L+5B5zTI2BwlwXmM+U3zReav3o0F8oUEFFZ42McDZYomOUziFmezgWyo251Uc1nyKJol7URCEvIYUEbHYaEGQi9C9egwCdVfHwiaajfjKMUcHcRacCylhWJbJDfq47EEDhYqoIWjHnwDXZPpPiChPQelLU+Cbm4w50FmYgkvFwpiWwCC/Um/SLcNElOC9RVj6qWpCiEMvRUK4zLpdKmPw8rVldy/qxjn60wLrVLWJIPLiZJRr3fsvnOHPvare+lB93tb37T20D82jqOt+zNuXhuNvNhp7X+PpHb3rvV9R5xjE2SpyCN9ffQO+GtWIZr5Xnytz4gTMIRYfys47/uJEXny/aQ/95tSUwmU+uRvSp/IHzQqZYpYrQmxAAAAAElFTkSuQmCC" /> {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[2024-06-06 23:35:35,121: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:35:35] "[35m[1mGET / HTTP/1.1[0m" 500 -]
[2024-06-06 23:35:35,525: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:35:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-06-06 23:36:06,253: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:36:06] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:37:15,072: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:37:15] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:37:18,893: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:37:18] "GET / HTTP/1.1" 200 -]
[2024-06-06 23:37:34,727: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.18.3:8080]
[2024-06-06 23:37:34,727: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-06 23:37:37,905: INFO: _internal: 192.168.18.3 - - [06/Jun/2024 23:37:37] "GET / HTTP/1.1" 200 -]
